### ISSUE TITLE
Let's use JSON

### ISSUE THREAD

**Issue by cydrobolt** [fedora-infra/asknot-ng#13]
JSON will allow us to have more flexibility with strings and data types, as well as the freedom of having long strings without worrying about YAML issues. 

JSON should work pretty well with Python, and I can probably write a YAML -> JSON script to convert our current questions.

**Comment by relrod** [comment]
I've generally seen it advised against using JSON for configuration files because it's meant to be a serialization format (to transfer data) rather than to be human readable/changeable.

I'm curious what issues we are seeing with long strings in YAML. You can do multi-line YAML strings like this:

To preserve newlines:

``` yaml
my_key: |
  foo bar
  baz buzz
```

To eat newlines:

``` yaml
my_key: >
  foo bar
  baz buzz
```

What flexibility in strings and data types is achieved by switching?

**Comment by ralphbean** [comment]
I'd add, I think we're only using stringy data types at the moment.  No numerics or booleans yet afaik.

**Comment by ralphbean** [comment]
Respectfully, I'm going to reject this issue.

YAML is nice to edit, in my opinion and JSON doesn't appear to give us anything we need (like types.. everything is a string to us in asknot-ng).  Thanks for suggesting this!
