### ISSUE TITLE
Developing openSUSE version of the site

### ISSUE THREAD

**Issue by hellcp** [fedora-infra/asknot-ng#165]
Hi,

I've started work on [openSUSE/asknot-ng](https://github.com/openSUSE/asknot-ng), and before I needlessly PR I'm curious if you would accept changes like these into upstream? We would most likely want to use our own weblate instance as well ([l10n.opensuse.org](https://l10n.opensuse.org)). I'm not sure how well double weblate integration in one repository works tbh, but maybe it's worth testing.

**Comment by Zlopez** [comment]
I'm not really a maintainer of this project, I was just the last one who worked on it. But I like to see collaboration like this much more and if you have anything that the Fedora asknot-ng could benefit from we would gladly see the PR. :-)

**Comment by hellcp** [comment]
I don't really have much to offer in terms of fixes to the script or template, but rather basically just openSUSE theme and data files

**Comment by Zlopez** [comment]
In this case I think this could stay in openSUSE fork

**Comment by justwheel** [comment]
I suspect that if we continue developing this site in Fedora, we would likely rebrand it to specifically "whatcanidoforfedora.org" although I could be persuaded otherwise.

Changes and improvements upstream are always welcome, but I agree with @Zlopez that maintaining theme-specific changes and data would be better suited for the openSUSE fork. With that in mind, I am going to close this issue, but feel free to open a new issue with further questions or send a Pull Request if you have changes to share.
