### ISSUE TITLE
asknot-ng does not link it to https://github.com/fedora-infra/asknot-ng

### ISSUE THREAD

**Issue by trishnaguha** [fedora-infra/asknot-ng#53]
On the bottom of the page http://whatcanidoforgnome.org/ , asknot-ng does not link it to https://github.com/fedora-infra/asknot-ng. It just redirects it to http://whatcanidoforgnome.org/ 
It only works for "open in a new tab".

**Comment by abhishekarora12** [comment]
http://whatcanidoforgnome.org has an iframe which redirects to http://gnome.schuirmann.net/, but the link works fine there, so i think the bug is in the iframe. 
Adding target='_top' in the iframe might fix it.

**Comment by cydrobolt** [comment]
This works for me. Is this still relevant?

**Comment by sils** [comment]
I'm still experiencing this.

**Comment by trishnaguha** [comment]
@sils1297 Can we get the source code? I am not able to find it.
Thanks :)

**Comment by sils** [comment]
This source code isn't stored anywhere, Alexandre (who has the domain) just
needs some time to fix it. I'll ping him again for sure.

**Comment by afranke** [comment]
The way this is setup is I simply configured the redirection with my domain registrar (gandi) and they do the iframe thing. I don't have my hands on the iframe code, so I can't fix that. The proper way to fix that would actually be to get rid of that redirection and have a proper DNS setup, because the iframe is also bad for SEO. I'd need a fixed IP instead of http://gnome.schuirmann.net/ for that.

**Comment by cydrobolt** [comment]
Ah, I see why I thought it was working. I have a habit of always using CTRL+click on links to open them in a new tab. Apparently, clicking on the link without the CTRL causes it to be broken.

**Comment by cydrobolt** [comment]
@afranke yes, it would be much more preferable to set up DNS to avoid using an `iframe`. It looks like an OpenShift configuration may work for your case.

Let me know if there's anything I can help with :)

**Comment by afranke** [comment]
@sils1297 is going to install it on Openshift and @puiterwijk will set up a proxy on the GNOME infrastructure to allow us to use both www and naked domain name.

**Comment by sils** [comment]
Speaking of which, it's up on http://askgnome-coalas.rhcloud.com/ .
@afranke , I am a bit short on free gears because I'm also using openshift
for evaluating a bigger project that might well expand over some gears, I'd
prefer if somebody else could provide the gear. I'm adding generic
OpenShift deployment information in a minute.

2015-10-28 22:06 GMT+01:00 Alexandre Franke notifications@github.com:

**Comment by afranke** [comment]
There wasn't much interest in keeping this, we didn't renew the domain name. @sils1297 you can drop the gear. This issue can probably be closed.

**Comment by sils** [comment]
Yep, assuming this is GNOME only this can be closed as the website doesn't really exist anynmore.
