### ISSUE TITLE
Custom page after all questions end

### ISSUE THREAD

**Issue by adtac** [fedora-infra/asknot-ng#71]
Currently (at least at whatcanidoforcoala.org) after the last option ends, the first option loops back. It would be great if we could have a custom page (so that we can redirect the user to the IRC/gitter page for more questions). Or if this feature already exists, how could we implement this?

**Comment by ralphbean** [comment]
You could add a special question at the end of the list that does this?  Or, do you want something more automatic (i.e., literally redirect the user once they loop past the last question?)

**Comment by adtac** [comment]
Would that special page still need to have the two options? (I'm sorry, I'm not experienced with this). If we can disable the options for that page, that's perfect.

**Comment by hypothesist** [comment]
Would that special page still need to have the two options? (I'm sorry, I'm not experienced with this). If we can disable the options for that page, that's perfect.

**Comment by Sadin** [comment]
@adtac So what you're asking is when they get to the end of the list on the main tier instead of having it loop back that it redirect. What I would say would be best is to try what @ralphbean mentioned and add a final page that suggests one checkout irc or even telegram ( provide links and possibly a irc instructions link ) but also gives them the choice to run by the options one more time and check out the top level again. 

Having an instant redirect might cause confusion and a loss of control feeling.

**Comment by adtac** [comment]
@Sadin thanks :+1: That _should_ do it, I think. We'll test it out.

BTW I'm closing this issue, I had no idea it's still open :P
