### ISSUE TITLE
Any details on how well this is working?

### ISSUE THREAD

**Issue by gundalow** [fedora-infra/asknot-ng#92]
Hi,
Apologies for slight miss use of GitHub issue, though I couldn't see any contact detail. Happy to be redirected else where.

Just found this project and it looks very cool. I like how you ask people what they are interested, rather than  telling them the things they could do.

Do you have any stats (or gut feel) on how well whatcanidoforfedora.org has been received and if it's had a positive effect?

I'm looking at Ansible's Contributor Experience, with a particular focus on reviews and Working Groups (SIGs)  and wondering what we can learn from the Fedora Project.

`gundalow` on Freenode

**Comment by ralphbean** [comment]
Hey, I think the mozilla people have had a *ton* of positive use of theirs.  I see this by how they act in IRC.  Existing contributors actively share deep links to their pages (like this one https://whatcanidoformozilla.org/#!/progornoprog/translate ) with new people when they come along.  I wanted to recreate that experience, but their tooling for their site wasn't flexible or re-usable.  That's why we made this.

I don't have any data, though, on what kind of hit-rate the site gets for Fedora.

@jwflory, do you have a sense for how broadly this site is used in Fedora circles?

**Comment by justwheel** [comment]
> @jwflory, do you have a sense for how broadly this site is used in Fedora circles?

I think it's one of the best-advertised on-boarding tools in the Fedora community. It even came up in a [Contributor Story](https://communityblog.fedoraproject.org/faw-2018-day-3-becoming-part-of-fedora-family-because-of-her/) on the Community Blog during Fedora Appreciation Week. I believe there is also other messaging used at conference presentations and booths for WCIDFF.

For page views, @mattdm or @nirik might have a better idea if we have any metrics like these available.

As to the impact it has had on the Fedora community, it's hard to say. It would be interesting to run a UI/UX summer mentored project for WCIDFF to explore this.

**Comment by hhlp** [comment]
Your issue is to old, the site was suffer some change across the time and your issue could be obsolete, if you problem come again, feel free to open a new one.
